# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
rojo = "rojo-rbx/rojo@7.4.1"
argon = "argon-rbx/argon@2.0.0-pre5"
stylua = "JohnnyMorganz/StyLua@0.20.0"
selene = "Kampfkarren/selene@0.26.1"
lune = "lune-org/lune@0.8.2"
# wally = "UpliftGames/wally@0.3.2"
